@extends('layouts.panel')
@section('title', 'Kelola Menu')
@section('content')
@include('admin.partials.menu-stock-tabs')
<div class="mb-4 flex flex-wrap items-start justify-between gap-3">
    <div class="flex flex-wrap gap-2">
        <a href="{{ route('admin.menus') }}" class="rounded-full px-3 py-1.5 text-xs font-semibold {{ request('kategori') ? 'bg-cream text-brand' : 'bg-brand text-white' }}">Semua</a>
        @foreach($categories as $category)<a href="{{ route('admin.menus',['kategori'=>$category->display_name]) }}" class="rounded-full px-3 py-1.5 text-xs font-semibold {{ request('kategori')===$category->display_name ? 'bg-brand text-white' : 'bg-cream text-brand' }}">{{ $category->display_name }}</a>@endforeach
    </div>
    <div class="flex gap-2">
        <details class="relative"><summary class="cursor-pointer list-none rounded-md border border-brand px-3 py-2 text-xs font-semibold text-brand">＋ Kategori</summary><form method="POST" action="{{ route('admin.categories.store') }}" class="absolute right-0 z-10 mt-2 w-64 rounded-lg border border-line bg-white p-3 shadow-lg">@csrf<label class="mb-1 block text-xs font-semibold">Nama kategori</label><input name="nama_kategori" required maxlength="100" class="mb-2 w-full rounded border border-line p-2 text-xs" placeholder="contoh: Teh"><button class="w-full rounded bg-brand p-2 text-xs text-white">Simpan Kategori</button></form></details>
        <details class="relative"><summary class="cursor-pointer list-none rounded-md bg-brand px-4 py-2 text-xs font-semibold text-white">＋ Tambah Menu Baru</summary><form method="POST" action="{{ route('admin.menus.store') }}" class="absolute right-0 z-10 mt-2 grid w-[min(90vw,360px)] gap-2 rounded-lg border border-line bg-white p-4 shadow-lg">@csrf<h3 class="font-display font-bold text-brand">Menu Baru</h3><input name="nama_menu" required maxlength="150" placeholder="Nama menu" class="rounded border border-line p-2 text-xs"><select name="id_kategori" required class="rounded border border-line p-2 text-xs"><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id_kategori }}">{{ $category->display_name }}</option>@endforeach</select><div class="grid grid-cols-2 gap-2"><input type="number" name="harga" min="0" step="500" required placeholder="Harga (Rp)" class="rounded border border-line p-2 text-xs"><input type="number" name="stok" min="0" required placeholder="Stok" class="rounded border border-line p-2 text-xs"></div><input type="number" name="batas_minimum" min="0" placeholder="Batas stok minimum" class="rounded border border-line p-2 text-xs"><textarea name="deskripsi" placeholder="Deskripsi menu (opsional)" class="rounded border border-line p-2 text-xs"></textarea><button class="rounded bg-brand p-2 text-xs font-semibold text-white">Simpan Menu</button></form></details>
    </div>
</div>
<div class="overflow-x-auto rounded-xl border border-line bg-white p-4"><table class="w-full min-w-[760px] text-left text-xs"><thead class="bg-cream text-brand"><tr>@foreach(['No','Nama Menu','Kategori','Harga','Stok','Status','Aksi'] as $h)<th class="px-3 py-2">{{ $h }}</th>@endforeach</tr></thead><tbody>
@forelse($menus as $i=>$item)<tr class="border-b border-line last:border-0"><td class="px-3 py-2.5">{{ $i+1 }}</td><td class="px-3 py-2.5 font-semibold">{{ $item['nama'] }}</td><td class="px-3">{{ $item['kategori'] }}</td><td class="px-3 font-semibold">Rp {{ number_format($item['harga'],0,',','.') }}</td><td class="px-3">{{ $item['stok'] }}</td><td class="px-3"><span class="rounded px-2 py-1 {{ $item['aktif'] ? 'bg-green-100 text-green-800' : 'bg-gray-200 text-gray-600' }}">{{ $item['aktif'] ? 'Aktif' : 'Habis' }}</span></td><td class="px-3"><div class="flex items-center gap-1"><details class="relative"><summary class="cursor-pointer list-none rounded bg-cream px-2 py-1 text-brand">Edit</summary><form method="POST" action="{{ route('admin.menus.update',$item['id']) }}" class="absolute right-0 z-10 grid w-72 gap-2 rounded-lg border border-line bg-white p-3 shadow-lg">@csrf @method('PUT')<input name="nama_menu" required value="{{ $item['nama'] }}" class="rounded border border-line p-2"><select name="id_kategori" class="rounded border border-line p-2">@foreach($categories as $category)<option value="{{ $category->id_kategori }}" @selected($category->id_kategori==$item['kategori_id'])>{{ $category->display_name }}</option>@endforeach</select><input type="number" name="harga" min="0" step="500" required value="{{ $item['harga'] }}" class="rounded border border-line p-2"><input type="number" name="stok" min="0" required value="{{ $item['stok'] }}" class="rounded border border-line p-2"><input type="number" name="batas_minimum" min="0" value="{{ $item['minimum'] }}" class="rounded border border-line p-2"><textarea name="deskripsi" class="rounded border border-line p-2">{{ $item['deskripsi'] }}</textarea><button class="rounded bg-brand p-2 text-white">Simpan Perubahan</button></form></details><form method="POST" action="{{ route('admin.menus.delete',$item['id']) }}" onsubmit="return confirm('Hapus menu {{ addslashes($item['nama']) }}?')">@csrf @method('DELETE')<button class="rounded border px-2 py-1">Hapus</button></form></div></td></tr>
@empty<tr><td colspan="7" class="p-8 text-center text-muted">Belum ada menu untuk kategori ini. Tambahkan menu baru untuk mulai.</td></tr>@endforelse
</tbody></table></div>
@endsection
